// Lista base de bolos (Quiosque): pares [regular, ifood]
export const bolosList = [
    ['BOLO AIPIM', 'BOLO AIPIM I'],
    ['BOLO AMENDOIM', 'BOLO AMENDOIM I'],
    ['BOLO AMENDOIM MINI', 'BOLO AMENDOIM MINI I'],
    ['BOLO BANANA AVEIA', 'BOLO BANANA AVEIA I'],
    ['BOLO BANANA', 'BOLO BANANA I'],
    ['BOLO BANANA MINI', 'BOLO BANANA MINI I'],
    ['BOLO BOLO', 'BOLO BOLO I'],
    ['BOLO BOLO MINI', 'BOLO BOLO MINI I'],
    ['BOLO CACAU INTEGRAL', 'BOLO CACAU INTEGRAL I'],
    ['BOLO CENOURA', 'BOLO CENOURA I'],
    ['BOLO CENOURA MINI', 'BOLO CENOURA MINI I'],
    ['BOLO CENOURA C', 'BOLO CENOURA C I'],
    ['BOLO CHOCOLATE', 'BOLO CHOCOLATE I'],
    ['BOLO CHOCOLATE MINI', 'BOLO CHOCOLATE MINI I'],
    ['BOLO CHOCOLATE C', 'BOLO CHOCOLATE C I'],
    ['BOLO CHUVA', 'BOLO CHUVA I'],
    ['BOLO CHUVA MINI', 'BOLO CHUVA MINI I'],
    ['BOLO COCO', 'BOLO COCO I'],
    ['BOLO COCO MINI', 'BOLO COCO MINI I'],
    ['BOLO FORMIGUEIRO', 'BOLO FORMIGUEIRO I'],
    ['BOLO FORMIGUEIRO MINI', 'BOLO FORMIGUEIRO MINI I'],
    ['BOLO FUBÁ', 'BOLO FUBÁ I'],
    ['BOLO FUBÁ MINI', 'BOLO FUBÁ MINI I'],
    ['BOLO FUBÁ C', 'BOLO FUBÁ C I'],
    ['BOLO LARANJA', 'BOLO LARANJA I'],
    ['BOLO LARANJA MINI', 'BOLO LARANJA MINI I'],
    ['BOLO LARANJA C', 'BOLO LARANJA C I'],
    ['BOLO LIMÃO', 'BOLO LIMÃO I'],
    ['BOLO LIMÃO MINI', 'BOLO LIMÃO MINI I'],
    ['BOLO MESCLADO', 'BOLO MESCLADO I'],
    ['BOLO MESCLADO MINI', 'BOLO MESCLADO MINI I'],
    ['BOLO MILHO', 'BOLO MILHO I'],
    ['BOLO MILHO MINI', 'BOLO MILHO MINI I'],
    ['BOLO NOZES', 'BOLO NOZES I'],
    ['BOLO NOZES MINI', 'BOLO NOZES MINI I']
];

// Bolos especiais (sem variante iFood mapeada)
export const specialBolos = [
    'BOLO SF BOLO DE BOLO',
    'BOLO SF CENOURA',
    'BOLO SF CHOCOLATE',
    'BOLO SF NOZES',
    'BOLO AIPIM TABULEIRO',
    'BOLINHO PRESENTE'
];
